/*
 *  dictionary RTCIdentityProvider {
 *   required GenerateAssertionCallback generateAssertion;
 *   required ValidateAssertionCallback validateAssertion;
 *  };
 *  
 */
class IdentityProvider
{
	constructor(config)
	{
		
	}
	
	/*
	 * generateAssertion of type GenerateAssertionCallback, required
	 *	A user agent invokes this method on the IdP to request the generation of an identity assertion.
	 *	
	 *	The IdP provides a promise that resolves to an RTCIdentityAssertionResult to successfully generate 
	 *	an identity assertion. Any other value, or a rejected promise, is treated as an error.
	 *	
	 *	callback GenerateAssertionCallback = Promise<RTCIdentityAssertionResult> (DOMString contents, DOMString origin, RTCIdentityProviderOptions options);
	 *	
	 *		contents of type DOMString
	 *			The contents parameter includes the information that the user agent wants covered by the identity assertion.
	 *			The IdP must treat contents as opaque string. A successful validation of the provided assertion must produce the same string.
	 *			
	 *		origin of type DOMString
	 *			The origin parameter identifies the origin of the RTCPeerConnection that triggered this request.
	 *			An IdP can use this information as input to policy decisions about use.
	 *			This value is generated by the user agent based on the origin of the document that created the RTCPeerConnection and therefore can be trusted to be correct.
	 *			
	 *		options of type RTCIdentityProviderOptions
	 *			This includes the options provided by the application when calling setIdentityProvider.
	 *			Though the dictionary is an optional argument to setIdentityProvider, default values are used as necessary when passing the value to the identity provider; see the definition of RTCIdentityProviderOptions for details.
	 */
	async generateAssertion(contents, orgin, options)
	{
		/*
		 *  dictionary RTCIdentityAssertionResult {
		 *   required RTCIdentityProviderDetails idp;		// An IdP provides these details to identify the IdP that validates the identity assertion. 
		 *							// This struct contains the same information that is provided to setIdentityProvider.
		 *   required DOMString                  assertion;	// An identity assertion.
		 *							// This is an opaque string that must contain all information necessary to assert identity.
		 *							// This value is consumed by the validating IdP.
		 * };
		 * 
		 * dictionary RTCIdentityProviderDetails {
		 *    required DOMString domain;			// The domain name of the IdP that validated the associated identity assertion.
		 *             DOMString protocol = "default";		// The protocol parameter used for the IdP.
		 *							// This attribute must contain only characters legal for inclusion in URIs [RFC3986].
		 * };
		 * 
		 */
		return {
			idp : {
				domain   : "",
				protocol : "default"
			},
			assertion : ""
		};
	}
	
	/*
	 * validateAssertion of type ValidateAssertionCallback, required
	 * 	A user agent invokes this method on the IdP to request the validation of an identity assertion.
	 * 	
	 *	The IdP returns a Promise that resolves to an RTCIdentityValidationResult to successfully validate an identity assertion and to provide the actual identity.
	 *	Any other value, or a rejected promise, is treated as an error.
	 *	
	 *	callback ValidateAssertionCallback = Promise<RTCIdentityValidationResult> (DOMString assertion, DOMString origin);
	 *	
	 *		assertion of type DOMString
	 *			The assertion parameter includes the assertion that was recovered from an a=identity in the session description;
	 *			that is, the value that was part of the RTCIdentityAssertionResult provided by the IdP that generated the assertion.
	 *			
	 *		origin of type DOMString
	 *			The origin parameter identifies the origin of the RTCPeerConnection that triggered this request. An IdP can use this information as input to policy decisions about use.
	 */
	async validateAssertion(assertion, origin)
	{
		/*
		 * dictionary RTCIdentityValidationResult {
		 *    required DOMString identity;	// The validated identity of the peer.
		 *    required DOMString contents;	// The payload of the identity assertion.
		 *					//  An IdP that validates an identity assertion must return the same string that was provided to the original IdP that generated the assertion.
		 *					// The user agent uses the contents string to determine if the identity assertion matches the session description.
		 * };
		 */
		return {
			identity : "",
			contents : ""
		};
	}
};

module.exports = IdentityProvider;